language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=docs
  - python: 3.6
    env: TOXENV=flake8
install:
- pip install tox
script: tox

jobs:
  include:
  - stage: deploy
    script: echo "Deploying on PyPi ..."
    env: TOXENV=none
    install:
    python: 3.6
    deploy:
      provider: pypi
      user: JosefFriedrich
      password:
        secure: iVFjzTEEOl2vTRApxaJ94ki6z1x1dOxLJ+PamXyNjcNMwS9Xnh6QT91zuirEpSfembASb3N7p8D6qPSgCFm1QhkMBKVzeq+PybN4k+y1ZnvOzArQYxsxKEbIVvCg9uknYVspL2c2DL6S1J7la05ofhBcngHe4jTFJNAO/XvGdcBHR/sGoFQrnIgC1ESU2epQqGBm2BJk9gwjw09tSpRlqocA9ysWiC/qkjYbXPm2jigU0EqFU56GdmqG79mfHZ5Kvtp986EJuhDAtJNxPdAAGGvAlVh3aU9oas5LM5YdiXM0U7DZZhnwtxeChFgXv9c55zyBOTE4tjUgqSfegAQDS6lvgCq4Gq8qe1BiP5whquh8BKGqaoMn7lCk16r8BXD8zZgFBeX95DIM4GXX64zzXoGOae0NhrrP7RR9iQ7S5KPEWysjlDP/cuhk2toA9mPdfoMOMfw5HNKKUwaAUytNcytv4xryXaH62LOcbAEzD3W5LN9VTlp3/6lEa+YSvXQ/Be6sj/MUVRPtp0YlckAUeFjKEvELBK+4UKEX+YFtNFyf6nOtLQh5woFvf+XelwwNN8TyXQ2YB0xdzzPg9NrlXofHa2CzQNs9D1H9sbsSImoxVqZ4ikwHDfsMn99eGkhXqX1Q9eSSOzfeLyYeiujXVoCfLL9RDQk3YWTAdU6UC3w=
      on:
        tags: true
