dist: trusty
sudo: required
language: python
python:
    - "2.7"
addons:
    apt:
        sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
        packages:
            - bash-completion
            - gir1.2-gst-plugins-base-1.0
            - gir1.2-gstreamer-1.0
            - gstreamer1.0-plugins-good
            - gstreamer1.0-plugins-bad
            - imagemagick
            - mp3gain
            - python-gi
            - python-gst-1.0
            - python3-gi
            - python3-gst-1.0
	    - unrar
install:
    - pip install .
script: python test.py
