dist: trusty
sudo: required
language: python
python:
    - "2.7"
install:
    - pip install .
script: python test.py


# Non-Python dependencies.
addons:
    apt:
        sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse"
            - sourceline: "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
        packages:
            - imagemagick
