"""
This type stub file was generated by pyright.
"""

import struct
from struct import pack
from mutagen._iff import IffChunk, IffContainerChunkMixin, IffFile, InvalidChunk

"""Resource Interchange File Format (RIFF)."""
class RiffChunk(IffChunk):
    """Generic RIFF chunk"""
    @classmethod
    def parse_header(cls, header): # -> tuple[Any, ...]:
        ...
    
    @classmethod
    def get_class(cls, id): # -> Type[RiffListChunk] | Type[Self@RiffChunk]:
        ...
    
    def write_new_header(self, id_, size): # -> None:
        ...
    
    def write_size(self): # -> None:
        ...
    


class RiffListChunk(RiffChunk, IffContainerChunkMixin):
    """A RIFF chunk containing other chunks.
    This is either a 'LIST' or 'RIFF'
    """
    def parse_next_subchunk(self):
        ...
    
    def __init__(self, fileobj, id, data_size, parent_chunk) -> None:
        ...
    


class RiffFile(IffFile):
    """Representation of a RIFF file"""
    def __init__(self, fileobj) -> None:
        ...
    


