"""
This type stub file was generated by pyright.
"""

from os import path

import sphinx

"""
Sphinx Read the Docs theme.

From https://github.com/ryan-roemer/sphinx-bootstrap-theme.
"""
__version__ = ...
__version_full__ = ...

def get_html_theme_path():  # -> str:
    """Return list of HTML theme paths."""
    ...

def setup(app): ...
